
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pg4.java
 *
 * Created on Nov 30, 2016, 10:03:31 AM
 */

/**
 *
 * @author system29
 */
public class pg4 extends javax.swing.JFrame {

    /** Creates new form pg4 */
    public pg4() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        q1 = new javax.swing.JTextField();
        q3 = new javax.swing.JTextField();
        chk4 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        chk2 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        chk1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        q2 = new javax.swing.JTextField();
        q4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ON_SHOP.COM");

        jPanel1.setLayout(null);

        q1.setFont(new java.awt.Font("Tahoma", 1, 12));
        q1.setText("1");
        q1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });
        jPanel1.add(q1);
        q1.setBounds(190, 190, 30, 30);

        q3.setFont(new java.awt.Font("Tahoma", 1, 12));
        q3.setText("1");
        q3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3ActionPerformed(evt);
            }
        });
        jPanel1.add(q3);
        q3.setBounds(190, 430, 30, 30);

        chk4.setBackground(new java.awt.Color(255, 255, 255));
        chk4.setFont(new java.awt.Font("Bodoni MT Black", 0, 11));
        chk4.setForeground(new java.awt.Color(102, 102, 255));
        chk4.setText("Tommy Hilfiger");
        jPanel1.add(chk4);
        chk4.setBounds(280, 330, 130, 23);

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Vijaya", 0, 52));
        jLabel1.setForeground(new java.awt.Color(0, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WATCHES");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 10, 270, 67);

        chk2.setBackground(new java.awt.Color(255, 255, 255));
        chk2.setFont(new java.awt.Font("Bodoni MT Black", 0, 11));
        chk2.setForeground(new java.awt.Color(102, 102, 255));
        chk2.setText("Sonata");
        chk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk2ActionPerformed(evt);
            }
        });
        jPanel1.add(chk2);
        chk2.setBounds(280, 120, 130, 23);

        chk3.setBackground(new java.awt.Color(255, 255, 255));
        chk3.setFont(new java.awt.Font("Bodoni MT Black", 0, 11));
        chk3.setForeground(new java.awt.Color(102, 102, 255));
        chk3.setText("Casio");
        chk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk3ActionPerformed(evt);
            }
        });
        jPanel1.add(chk3);
        chk3.setBounds(30, 330, 140, 23);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11));
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casio-Classic-Multi-Dials-MTP-1037366-1-2f6a2.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Price Rs.5000/-"));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 350, 137, 150);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11));
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fastrack.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Price Rs.3000/-"));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 140, 140, 170);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11));
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sonata-7098BM01-Men-s-Watch-SDL081814647-1-770c7.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Price Rs.2500/-"));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 140, 133, 170);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("Qty");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(180, 100, 40, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-to-cart-dark.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(370, 540, 65, 70);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backk.jpg"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 540, 87, 65);

        chk1.setBackground(new java.awt.Color(255, 255, 255));
        chk1.setFont(new java.awt.Font("Bodoni MT Black", 0, 11));
        chk1.setForeground(new java.awt.Color(102, 102, 255));
        chk1.setText("Fastrack");
        chk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk1ActionPerformed(evt);
            }
        });
        jPanel1.add(chk1);
        chk1.setBounds(30, 120, 140, 23);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11));
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tommy.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Price Rs.10000/-"));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 350, 130, 150);

        q2.setFont(new java.awt.Font("Tahoma", 1, 12));
        q2.setText("1");
        q2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2ActionPerformed(evt);
            }
        });
        jPanel1.add(q2);
        q2.setBounds(450, 190, 30, 30);

        q4.setFont(new java.awt.Font("Tahoma", 1, 12));
        q4.setText("1");
        q4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4ActionPerformed(evt);
            }
        });
        jPanel1.add(q4);
        q4.setBounds(430, 440, 30, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("Qty");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 100, 40, 40);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PicsArt_12-03-12.42.04bc.png"))); // NOI18N
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 530, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try
{
    Class.forName("java.sql.Driver");
    String uid="root";
    String pswd="root";
    String db_url="jdbc:mysql://localhost:3306/system24";
    Connection con=(Connection)DriverManager.getConnection(db_url,uid,pswd);
    Statement stmt=(Statement) con.createStatement();

   int price=0,qty=0,amount=0;
   String items="";
   int qt1=Integer.parseInt(q1.getText());
int qt2=Integer.parseInt(q2.getText());
int qt3=Integer.parseInt(q3.getText());
int qt4=Integer.parseInt(q4.getText());

if (chk1.isSelected())
{
      price=3000;
      qty=Integer.parseInt(q1.getText());
      amount=price*qty;
      items="Fastrack";
      pg1.x+=1;
      stmt.executeUpdate("Insert into cart values("+pg1.x+",'"+items+"',"+qty+","+price+","+amount+")");

}
if (chk2.isSelected())
{
      price=2500;
      qty=Integer.parseInt(q2.getText());
      amount=price*qty;
      items="Sonata";
      pg1.x+=1;
      stmt.executeUpdate("Insert into cart values("+pg1.x+",'"+items+"',"+qty+","+price+","+amount+")");
}
if (chk3.isSelected())
{
      price=5000;
      qty=Integer.parseInt(q3.getText());
      amount=price*qty;
      items="Casio";
      pg1.x+=1;
      stmt.executeUpdate("Insert into cart values("+pg1.x+",'"+items+"',"+qty+","+price+","+amount+")");
}
if (chk4.isSelected())
{
      price=10000;
      qty=Integer.parseInt(q4.getText());
      amount=price*qty;
      items="Tommy Hilfiger";
      pg1.x+=1;
      stmt.executeUpdate("Insert into cart values("+pg1.x+",'"+items+"',"+qty+","+price+","+amount+")");
      
}


    JOptionPane.showMessageDialog(null,"Added to cart");

}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
pg3 a=new pg3();
a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1ActionPerformed

    private void q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4ActionPerformed

    private void chk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk1ActionPerformed

    private void q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3ActionPerformed

    private void chk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk2ActionPerformed

    private void q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2ActionPerformed

    private void chk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pg4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JCheckBox chk4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    // End of variables declaration//GEN-END:variables

}
